/* Prefer the JSON the bundler inlined; fall back to fetch when the folder is served
   directly. One call site, both modes — the source tree and the published artifact never
   diverge, and a bundled page needs no network at all. */
function loadData(file) {
  var tag = document.querySelector(
    'script[type="application/json"][data-pv-file="' + file + '"]');
  if (tag) return Promise.resolve(JSON.parse(tag.textContent));
  return fetch('data/' + file, {cache: 'no-cache'}).then(function (r) {
    if (!r.ok) throw new Error(r.status + ' ' + r.statusText);
    return r.json();
  });
}

/* =========================================================================
   PIC portfolio timeline
   Vanilla JS, inline SVG. No dependencies, no build step. Everything on this
   page derives from data/timeline.json, which is generated by
   tools/build-timeline-web.py from the merged event inventory. Do not edit the
   JSON by hand — regenerate it.

   Structure
     1  data + scales
     2  layout        lane bands, collision packing, label placement
     3  render        svg (wide) / small multiples (narrow); 3a cadence, 3b prologue
     4  table + csv
     5  interaction   filters, hover, panel
   ========================================================================= */

(() => {
  'use strict';

  // Below this the lanes stop being readable as lanes and a card list is honest.
  const CARD_BREAKPOINT = 900;
  // The window. Most public events fall inside it; the older ones feed the cadence
  // chart's "before" bars instead of compressing the axis to nothing.
  const WIN_FROM = new Date('2023-01-01');
  const WIN_TO = new Date('2030-01-01');
  const NOW = new Date('2026-08-13');
  const NOW_ISO = '2026-08-13';
  const NOW_LBL = '13 Aug 2026';
  const DESIG_ISO = '2023-10-23';

  /* Page-local categorical palette, declared with a legend (five lanes is past the
     three-hue story limit). Rebuilt 2026-08-28: Designations and Startups used to be two
     teals 0.9 L* apart, which is one color at dot and chip size, and the Designations
     teal was the same hex as the cadence chart's "since designation" story bar. This set
     drops teal from four of the five lanes, spreads them over 24.7-48.5 L* (min pairwise
     gap 5.4) and keeps every one at or above 4.5:1 on white, because these hues are read
     as text in the lane names, the chips and the table. */
  const LANE_COLOR = {
    desig: '#06414B', rd: '#78304F', work: '#9A6A08', startup: '#B0421A', infra: '#435F0B',
  };
  // Horizon is a FILTER facet only (the chips below the H2). It no longer sizes the
  // dots: three barely distinguishable radii read as importance, which the data never
  // meant. One radius for every event; status is the fill, lane is the color.
  const HZ = {
    quick: { label: 'Under a year' },
    mid: { label: 'One to three years' },
    long: { label: 'Three years or more' },
  };
  const HZ_ORDER = ['quick', 'mid', 'long'];
  const DOT_R = 7;

  let DATA = null, IN = [], PRE = [];
  let HER = null;                       // heritage.json — the prologue's data
  // 12.3 L* apart, so the two heritage rows separate in grayscale as well as by row.
  const HCOL = { heritage: '#3B3C38', discoveries: '#8E3B62' };
  const offLane = new Set(), offHz = new Set();
  let mode = null, lastW = 0, tip = null;
  let tableExpanded = false;

  const viz = document.getElementById('viz');
  const panel = document.getElementById('panel');
  const scrim = document.getElementById('scrim');

  const NS = 'http://www.w3.org/2000/svg';
  const el = (t, a, txt) => {
    const n = document.createElementNS(NS, t);
    for (const k in a) if (a[k] != null) n.setAttribute(k, a[k]);
    if (txt != null) n.textContent = txt;
    return n;
  };
  const h = (t, a, kids) => {
    const n = document.createElement(t);
    for (const k in (a || {})) {
      if (k === 'class') n.className = a[k];
      else if (k === 'text') n.textContent = a[k];
      else if (k.startsWith('on')) n.addEventListener(k.slice(2), a[k]);
      else if (a[k] != null) n.setAttribute(k, a[k]);
    }
    (kids || []).forEach((c) => n.appendChild(c));
    return n;
  };
  /* A paper plate behind SVG text that must sit over other ink. data-pv-plated marks
     the text as deliberately plated so the collide gate does not report it. */
  const plated = (g, s, x, y, opts) => {
    const o = opts || {};
    const fs = o.cw || 6.6;                 // rough char width for the plate
    const wpx = s.length * fs + 8;
    const anchor = o.anchor || 'start';
    const px = anchor === 'end' ? x - wpx + 4 : anchor === 'middle' ? x - wpx / 2 : x - 4;
    g.appendChild(el('rect', { x: px, y: y - 11.5, width: wpx, height: 15,
      fill: '#fff', opacity: .92, rx: 2 }));
    const t = el('text', { class: o.class || 'ann', x, y,
      'text-anchor': anchor, 'data-pv-plated': '1' }, s);
    if (o.fill) t.setAttribute('fill', o.fill);
    g.appendChild(t);
    return t;
  };

  /* ------------------------------------------------------------- 1 data */

  // Show the date at the precision it is actually known to. An event recorded
  // only to its year is not a 1 January event, and drawing it as one is a lie
  // the reader cannot see.
  const MON = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  function showDate(e) {
    const d = new Date(e.date);
    if (e.datePrecision === 'day') return `${d.getUTCDate()} ${MON[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
    if (e.datePrecision === 'month') return `${MON[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
    return e.dateDisplay;
  }
  const precNote = (e) => e.datePrecision === 'day' ? null
    : e.datePrecision === 'month' ? 'Recorded to the month; placed mid-month.'
    : 'Recorded to the year only; placed mid-year.';

  const visible = (e) => !offLane.has(e.laneKey) && !(e.horizon && offHz.has(e.horizon));

  /* ----------------------------------------------------------- 2 layout */

  // Pack events into sub-rows inside their lane so dots never sit on top of each
  // other. Greedy first-fit by x — the same approach a Gantt uses for bars.
  function pack(events, x, minGap) {
    const rowsEnd = [];
    events.forEach((e) => {
      const cx = x(new Date(e.date));
      let row = rowsEnd.findIndex((end) => cx - end >= minGap);
      if (row === -1) { row = rowsEnd.length; rowsEnd.push(-1e9); }
      rowsEnd[row] = cx;
      e._row = row; e._cx = cx;
    });
    return Math.max(1, rowsEnd.length);
  }

  /* ----------------------------------------------------------- 3 render */

  function render() {
    const w = viz.clientWidth;
    if (!w) return;
    const want = w < CARD_BREAKPOINT ? 'cards' : 'diagram';
    if (want === mode && Math.abs(w - lastW) < 2) return;
    mode = want; lastW = w;
    viz.textContent = '';
    (want === 'cards' ? renderPanels : renderDiagram)(w);
  }

  /* The three page-wide moments, drawn as labeled vertical rules (the chart-craft
     "labeled event line" idiom). Label STRINGS are editorial; the dates come from
     the events themselves and are asserted in claims.json. */
  const RULES = [
    // "1 of 31" is the inventory's phrasing and reads as a rank; on the chart it is spelled
    // out as membership, which is what it means.
    { date: '2023-10-23', label: '23 Oct 2023 · EDA designates the Tech Hub, one of 31 nationwide', tier: 0 },
    { date: '2024-07-02', label: '2 Jul 2024 · the $51M implementation grant', tier: 1 },
    { date: '2024-12-01', label: 'Dec 2024 · five company R&D awards begin', tier: 2 },
  ];

  function renderDiagram(W) {
    const L = { left: 208, right: 26, top: 112, bot: 96, laneGap: 10, rowH: 30, padY: 16 };
    const TIER_Y = [16, 34, 52];
    const plotW = W - L.left - L.right;
    const span = WIN_TO - WIN_FROM;
    const x = (d) => L.left + ((Math.min(Math.max(d, WIN_FROM), WIN_TO) - WIN_FROM) / span) * plotW;

    const lanes = DATA.lanes.map((ln) => {
      const evs = IN.filter((e) => e.laneKey === ln.key && visible(e))
        .sort((a, b) => new Date(a.date) - new Date(b.date));
      const nRows = pack(evs, x, 19);
      return { ...ln, evs, nRows, all: IN.filter((e) => e.laneKey === ln.key).length };
    });

    let y = L.top;
    lanes.forEach((ln) => { ln.y = y; ln.h = ln.nRows * L.rowH + L.padY * 2; y += ln.h + L.laneGap; });
    const laneBot = y - L.laneGap;
    const H = y + L.bot;

    const svg = el('svg', { viewBox: `0 0 ${W} ${H}`, role: 'img',
      'aria-label': ariaSummary() });

    // year gridlines + labels (labels sit just above the lanes, under the rule labels)
    for (let yr = 2023; yr <= 2030; yr++) {
      const gx = x(new Date(`${yr}-01-01`));
      svg.appendChild(el('line', { class: 'axis-rule', x1: gx, x2: gx, y1: L.top - 12, y2: laneBot }));
      if (yr < 2030) svg.appendChild(el('text', { class: 'axis-y', x: gx + 7, y: L.top - 18 }, yr));
    }

    // lane bands + names
    lanes.forEach((ln, i) => {
      svg.appendChild(el('rect', { class: 'lane-band' + (i % 2 ? ' alt' : ''),
        x: 0, y: ln.y, width: W, height: ln.h, rx: 8 }));
      svg.appendChild(el('text', { class: 'lane-name', x: 0, y: ln.y + 24,
        fill: LANE_COLOR[ln.key] }, ln.name));
      const shown = ln.evs.length;
      svg.appendChild(el('text', { class: 'lane-count', x: 0, y: ln.y + 45 },
        shown === ln.all ? `${shown} events` : `${shown} of ${ln.all} events`));
    });

    // a light tint over everything right of Today: the promise zone
    const nx = x(NOW);
    svg.appendChild(el('rect', { class: 'fwd-zone', x: nx, y: L.top - 12,
      width: L.left + plotW - nx, height: laneBot - L.top + 12 }));

    // the three labeled event rules, behind the dots
    RULES.forEach((rl) => {
      const rx = x(new Date(rl.date));
      const ty = TIER_Y[rl.tier];
      svg.appendChild(el('line', { class: 'ev-rule', x1: rx, x2: rx, y1: ty + 5, y2: laneBot }));
      svg.appendChild(el('text', { class: 'rule-lab', x: rx + 6, y: ty }, rl.label));
    });

    // the "as of" rule — dots to its right are scheduled, not delivered
    svg.appendChild(el('line', { class: 'now-rule', x1: nx, x2: nx, y1: L.top - 12, y2: laneBot }));

    // events
    const pos = {};
    lanes.forEach((ln) => {
      const g = el('g', {});
      ln.evs.forEach((e) => {
        const cy = ln.y + L.padY + e._row * L.rowH + L.rowH / 2;
        pos[e.id] = { x: e._cx, y: cy };
        const node = el('g', { class: 'ev' + (e.delivered ? '' : ' fwd'), 'data-id': e.id,
          style: `--c:${LANE_COLOR[ln.key]}`,
          tabindex: '0', role: 'button',
          'aria-label': `${showDate(e)}. ${e.title}.` + (e.delivered ? '' : ' Scheduled, not delivered.') });
        node.appendChild(el('circle', { class: 'hit', cx: e._cx, cy, r: DOT_R + 7 }));
        node.appendChild(el('circle', { class: 'dot', cx: e._cx, cy, r: DOT_R, fill: LANE_COLOR[ln.key],
          stroke: e.delivered ? '#fff' : LANE_COLOR[ln.key] }));
        // A white ring on a pale lane band still needs an anchor at small radii, or it
        // reads as a hole in the chart rather than a mark on it.
        if (!e.delivered) node.appendChild(el('circle', { class: 'pip', cx: e._cx, cy, r: 1.6,
          fill: LANE_COLOR[ln.key] }));
        g.appendChild(node);
      });
      svg.appendChild(g);
    });

    /* Leader-line labels for two single-dot moments (drawn last, never occluded).
       Skipped when a filter hides the dot — a label with no mark is a lie. */
    const ann = el('g', {});
    const nsf = pos['E205'];
    if (nsf) {
      ann.appendChild(el('line', { class: 'leader', x1: nsf.x, x2: nsf.x,
        y1: 78, y2: nsf.y - DOT_R - 3 }));
      plated(ann, '14 Jul 2026 · NSF backs NEO-SMART with $160M', nsf.x - 6, 72,
        { anchor: 'end', class: 'ann' });
    }
    const pf = pos['F29'];
    if (pf) {
      // the leader slopes on purpose: a flat hairline would read as an axis
      ann.appendChild(el('line', { class: 'leader', x1: pf.x + DOT_R + 2, x2: pf.x + 16,
        y1: pf.y - 5, y2: pf.y - 13 }));
      plated(ann, 'pilot facility ready · Nov 2027', pf.x + 20, pf.y - 12, { class: 'ann' });
    }
    svg.appendChild(ann);

    /* The on-chart takeaway, in the bottom margin right of Today. Counts are computed
       from the visible events so the sentence stays true under filters. */
    svg.appendChild(el('text', { class: 'now-lab', x: nx + 10, y: laneBot + 22 },
      `Today · ${NOW_LBL}`));
    promiseLines().forEach((s, i) => {
      svg.appendChild(el('text', { class: 'ann', x: nx + 10, y: laneBot + 42 + i * 17 }, s));
    });

    viz.appendChild(svg);
    wireEvents(svg);
    buildLegend();
  }

  /* The same four lines under both layouts, computed from the visible events so a filter
     can never leave the sentence describing dots that are hidden. */
  function promiseLines() {
    const sched = IN.filter((e) => visible(e) && !e.delivered);
    const near = sched.filter((e) => e.date < '2027-01-01').length;
    const far = sched.filter((e) => e.date >= '2027-01-01');
    const ends = far.filter((e) => /end|completion/.test(e.title.toLowerCase())).length;
    const pilot = far.some((e) => e.id === 'F29');
    return ['Everything right of Today is a promise:',
      `${sched.length} scheduled dates, ${near} due by end-2026;`,
      `the other ${far.length}, 2027 to 2029, are ${pilot ? 'the pilot' : 'award and'}`,
      pilot ? `plant and ${ends} award clocks running out.` : 'project clocks running out.'];
  }

  const M_RULES = [
    { date: '2023-10-23', label: 'Oct 2023 · designation' },
    { date: '2024-07-02', label: 'Jul 2024 · $51M grant' },
    { date: '2024-12-01', label: 'Dec 2024 · R&D awards begin' },
  ];

  /* MOBILE, chart 3. Until 2026-08-28 a phone got 87 stacked cards, about 14,000px, under a
     subtitle promising hollow dots, a Today rule and vertical event rules that were not on
     the screen. The swimlane is re-laid-out as five small multiples instead: the lane names
     become panel headings so the plot keeps the full width, and the shared axis, the Today
     rule, the tinted promise zone and the three labeled event rules run through all five.
     Every one of the 87 dots is still drawn, still solid-or-hollow, still tappable. */
  function renderPanels(W) {
    // TOP has to clear three tiers of rule label AND the year row under them; at 78 the
    // "Dec 2024 · R&D awards begin" plate sat on the year labels and hid four of them.
    const RIGHT = 8, TOP = 96, ROW = 20, HEADH = 24, GAP = 16, BOT = 104;
    const TIER_Y = [14, 32, 50];
    /* THE SCALE IS INSET BY THE WIDEST MARK'S OWN RADIUS. A dot is drawn AROUND its x, so
       a time scale that starts at x=0 puts half of every mark at the window's opening
       date outside the box: the first event's 13-unit tap target sat 10.8 units left of
       the viewBox and its 6-unit dot 3.8. The wide layout never showed this because it
       has a lane-name column; the panel layout moved the names above the plot to win the
       full width and took the margin away with them. At 1440 overflow:visible lets that
       ink land in the page gutter, but this layout only runs below ~900px, where the
       shared sheet's overflow-x:auto box CLIPS it — and it is the TAP TARGET, so what was
       lost was not decoration. Written off the radii rather than typed, so the inset
       cannot drift from the marks it exists to hold. */
    const HIT_R = 13, DOT_R = 6;
    const LEFT = HIT_R;
    const plotW = W - RIGHT - LEFT, plotR = LEFT + plotW;
    const span = WIN_TO - WIN_FROM;
    const x = (d) => LEFT + ((Math.min(Math.max(d, WIN_FROM), WIN_TO) - WIN_FROM) / span) * plotW;

    const lanes = DATA.lanes.map((ln) => {
      const evs = IN.filter((e) => e.laneKey === ln.key && visible(e))
        .sort((a, b) => new Date(a.date) - new Date(b.date));
      return { ...ln, evs, nRows: pack(evs, x, 15), all: IN.filter((e) => e.laneKey === ln.key).length };
    });
    let y = TOP;
    lanes.forEach((ln) => { ln.y = y; ln.h = HEADH + ln.nRows * ROW + 8; y += ln.h + GAP; });
    const laneBot = y - GAP;
    const H = laneBot + BOT;

    const svg = el('svg', { viewBox: `0 0 ${W} ${H}`, role: 'img', 'aria-label': ariaSummary() });

    /* Paint order matters and cost a redraw to find: the panel grounds go down FIRST, so
       the shared gridlines, the promise tint, the three event rules and the Today rule all
       run visibly ACROSS the five panels instead of disappearing behind them. */
    lanes.forEach((ln) => {
      svg.appendChild(el('rect', { class: 'pnl-band', x: 0, y: ln.y + HEADH - 6,
        width: W, height: ln.h - HEADH + 6, rx: 6 }));
    });

    for (let yr = 2023; yr <= 2030; yr++) {
      const gx = x(new Date(`${yr}-01-01`));
      svg.appendChild(el('line', { class: 'axis-rule', x1: gx, x2: gx, y1: TOP - 20, y2: laneBot }));
      if (yr < 2030) svg.appendChild(el('text', { class: 'm-axis', x: gx + 4, y: TOP - 26 }, yr));
    }

    const nx = x(NOW);
    svg.appendChild(el('rect', { class: 'fwd-zone', x: nx, y: TOP - 20,
      width: plotR - nx, height: laneBot - TOP + 20 }));

    M_RULES.forEach((rl, i) => {
      const rx = x(new Date(rl.date));
      svg.appendChild(el('line', { class: 'm-rule', x1: rx, x2: rx, y1: TIER_Y[i] + 5, y2: laneBot }));
      plated(svg, rl.label, rx + 5, TIER_Y[i], { class: 'm-rule-lab', cw: 6.2 });
    });
    svg.appendChild(el('line', { class: 'now-rule', x1: nx, x2: nx, y1: TOP - 20, y2: laneBot }));

    lanes.forEach((ln) => {
      svg.appendChild(el('text', { class: 'pnl-name', x: 0, y: ln.y + 12,
        fill: LANE_COLOR[ln.key] }, ln.name));
      svg.appendChild(el('text', { class: 'pnl-count', x: plotR, y: ln.y + 12,
        'text-anchor': 'end' },
        ln.evs.length === ln.all ? `${ln.evs.length}` : `${ln.evs.length} of ${ln.all}`));
      const g = el('g', {});
      ln.evs.forEach((e) => {
        const cy = ln.y + HEADH + 6 + e._row * ROW;
        const node = el('g', { class: 'ev' + (e.delivered ? '' : ' fwd'), 'data-id': e.id,
          style: `--c:${LANE_COLOR[ln.key]}`, tabindex: '0', role: 'button',
          'aria-label': `${showDate(e)}. ${e.title}.` + (e.delivered ? '' : ' Scheduled, not delivered.') });
        node.appendChild(el('circle', { class: 'hit', cx: e._cx, cy, r: HIT_R }));
        node.appendChild(el('circle', { class: 'dot', cx: e._cx, cy, r: DOT_R, fill: LANE_COLOR[ln.key],
          stroke: e.delivered ? '#fff' : LANE_COLOR[ln.key] }));
        if (!e.delivered) node.appendChild(el('circle', { class: 'pip', cx: e._cx, cy, r: 1.5,
          fill: LANE_COLOR[ln.key] }));
        g.appendChild(node);
      });
      svg.appendChild(g);
    });

    svg.appendChild(el('text', { class: 'now-lab', x: 0, y: laneBot + 22 }, `Today · ${NOW_LBL}`));
    promiseLines().forEach((s, i) => {
      svg.appendChild(el('text', { class: 'ann', x: 0, y: laneBot + 42 + i * 16 }, s));
    });

    viz.appendChild(svg);
    wireEvents(svg);
    buildLegend();
  }

  function ariaSummary() {
    const n = IN.filter(visible).length;
    const fwd = IN.filter((e) => visible(e) && !e.delivered).length;
    return `Timeline of ${n} public events from 2023 to 2029, in five workstream lanes: ` +
      DATA.lanes.map((l) => l.name).join(', ') + '. Each dot is one dated event; all dots are ' +
      `the same size. ${fwd} events are hollow because they are scheduled, not delivered. ` +
      'A dashed rule marks 13 August 2026, and labeled vertical rules mark the October 2023 ' +
      'designation, the July 2024 implementation grant and the December 2024 R&D award starts. ' +
      'The same record is in the table below.';
  }

  /* ---------------------------------------------- 3a the cadence comparison */
  // Delivered public events per year, before and after the designation, from the
  // same record that feeds the calendar. CTX rows (century-scale context) excluded;
  // the caveat beside the chart carries the record-keeping asymmetry.
  const cadBox = document.getElementById('cadence');
  let cadW = 0;

  function cadenceData() {
    const rec = PRE.filter((e) => e.tier !== 'CTX' && e.delivered)
      .concat(IN.filter((e) => e.delivered));
    const years = [2021, 2022, 2023, 2024, 2025, 2026];
    const rows = years.map((yr) => {
      const inYr = rec.filter((e) => +e.date.slice(0, 4) === yr);
      return { yr,
        before: inYr.filter((e) => e.date < DESIG_ISO).length,
        since: inYr.filter((e) => e.date >= DESIG_ISO).length };
    });
    const before = rows.reduce((s, r) => s + r.before, 0);
    const since = rows.reduce((s, r) => s + r.since, 0);
    return { rows, before, since };
  }

  function renderCadence() {
    if (!cadBox || !DATA) return;
    const W = cadBox.clientWidth;
    if (!W || Math.abs(W - cadW) < 2) return;
    cadW = W;
    cadBox.textContent = '';
    const { rows, before, since } = cadenceData();
    const narrow = W < 560;
    const m = { t: 40, r: 12, b: narrow ? 56 : 44, l: 34 };
    const Hpx = narrow ? 230 : 260;
    const w = W - m.l - m.r, hp = Hpx - m.t - m.b;
    const yMax = Math.max(...rows.map((r) => r.before + r.since)) + 4;
    const ys = (v) => m.t + hp - (v / yMax) * hp;
    const bw = Math.min(72, (w / rows.length) * 0.58);
    const cx = (i) => m.l + (w / rows.length) * (i + 0.5);

    const svg = el('svg', { viewBox: `0 0 ${W} ${Hpx}`, role: 'img',
      'aria-label': `Bar chart of delivered public events per year, 2021 to 2026: ` +
        rows.map((r) => `${r.yr}: ${r.before + r.since}`).join(', ') +
        `. ${before} events fall before the 23 October 2023 designation and ${since} after; ` +
        '2026 is counted through 13 August.' });

    // y gridlines
    [0, 10, 20, 30].forEach((v) => {
      if (v > yMax) return;
      svg.appendChild(el('line', { class: 'axis-rule', x1: m.l, x2: W - m.r,
        y1: ys(v), y2: ys(v) }));
      svg.appendChild(el('text', { class: 'axis-y cad-tick', x: m.l - 8, y: ys(v) + 4,
        'text-anchor': 'end' }, String(v)));
    });

    rows.forEach((r, i) => {
      const xc = cx(i);
      let top = ys(0);
      if (r.before) {
        const y1 = ys(r.before);
        svg.appendChild(el('rect', { class: 'cad-pre', x: xc - bw / 2, y: y1,
          width: bw, height: top - y1 }));
        top = y1 - 2;
      }
      if (r.since) {
        const y1 = top - (ys(0) - ys(r.since));
        // 2026 is eight and a half months, not twelve. A partial period drawn at full
        // saturation reads as a complete one; lighten it and tag it under the axis.
        svg.appendChild(el('rect', { class: 'cad-post' + (r.yr === 2026 ? ' partial' : ''),
          x: xc - bw / 2, y: y1, width: bw, height: ys(0) - ys(r.since) }));
        top = y1;
      }
      svg.appendChild(el('text', { class: 'cad-val', x: xc, y: top - 6,
        'text-anchor': 'middle' }, String(r.before + r.since)));
      svg.appendChild(el('text', { class: 'axis-y', x: xc, y: ys(0) + 18,
        'text-anchor': 'middle' }, String(r.yr)));
      if (r.yr === 2023) svg.appendChild(el('text', { class: 'cad-note', x: xc,
        y: ys(0) + (narrow ? 34 : 33), 'text-anchor': 'middle' }, 'designation · 23 Oct'));
      if (r.yr === 2026) svg.appendChild(el('text', { class: 'cad-note', x: xc,
        y: ys(0) + (narrow ? 34 : 33), 'text-anchor': 'middle' }, 'to 13 Aug'));
    });

    // the two-phase annotation, stacked over the short early bars
    svg.appendChild(el('text', { class: 'ann cad-ann-pre', x: m.l + 4, y: m.t + 8 },
      `before · ${before} events in 34 months`));
    svg.appendChild(el('text', { class: 'ann cad-ann-post', x: m.l + 4, y: m.t + 28 },
      `since · ${since} delivered in 34 months`));

    cadBox.appendChild(svg);

    const pl = document.getElementById('pre-list');
    if (pl && !pl.textContent) {
      const bef = PRE.filter((e) => e.tier !== 'CTX' && e.delivered)
        .concat(IN.filter((e) => e.delivered && e.date < DESIG_ISO))
        .sort((a, b) => a.date < b.date ? -1 : 1);
      pl.appendChild(h('b', { text: `The ${bef.length} before: ` }));
      pl.appendChild(document.createTextNode(
        bef.map((e) => `${showDate(e)}, ${e.title}`).join(' · ') + '.'));
    }
  }

  /* ------------------------------------------------ 3b the prologue: why here */
  // The heritage rows sit on an ERA-BANDED axis, not the 2023–2029 linear scale: five
  // era columns of equal width, events placed linearly inside their column. 1898–2012 on
  // the operating record's scale would compress to nothing; a linear 114-year axis would
  // put 11 of 32 marks in one 30-year stretch. Equal era columns are the honest middle —
  // and the columns are labeled with their years so nobody reads the axis as linear.
  const proBox = document.getElementById('pro-viz');
  let proMode = null, proW = 0, ptip = null;

  const yearFrac = (e) => {
    const d = new Date(e.date);
    return e.year + (e.datePrecision === 'day' || e.datePrecision === 'month'
      ? (d.getUTCMonth() + (d.getUTCDate() - 1) / 31) / 12 : 0.5);
  };
  function packBy(events, xf, minGap) {
    const rowsEnd = [];
    events.forEach((e) => {
      const cx = xf(e);
      let row = rowsEnd.findIndex((end) => cx - end >= minGap);
      if (row === -1) { row = rowsEnd.length; rowsEnd.push(-1e9); }
      rowsEnd[row] = cx; e._row = row; e._cx = cx;
    });
    return Math.max(1, rowsEnd.length);
  }
  const hDate = (e) => e.dateDisplay;
  const hKind = (e) => (HER.collections.find((c) => c.key === e.collection) || {}).name || e.collection;

  /* Named labels for the load-bearing heritage events. Hand-authored strings; the
     dates and rows they name are asserted in claims.json. Each label sits in the
     annotation band under its row block, with a short leader to its dot. */
  const HANN = [
    { id: 'H-002', text: '1898 · Goodyear founded', anchor: 'start' },
    { id: 'H-009e', text: '1991 · NSF ALCOM science center', anchor: 'middle' },
    { id: 'D-001', text: '1926 · Semon plasticizes PVC', anchor: 'middle' },
    { id: 'D-003', text: '1963 · first polymer department', anchor: 'middle' },
    { id: 'D-009', text: '2012 · the last proven row', anchor: 'end' },
  ];

  function renderPrologue() {
    if (!HER || !proBox) return;
    const W = proBox.clientWidth;
    if (!W) return;
    const want = W < CARD_BREAKPOINT ? 'cards' : 'diagram';
    if (want === proMode && Math.abs(W - proW) < 2) return;
    proMode = want; proW = W;
    proBox.textContent = '';
    (want === 'cards' ? renderHCompact : renderHDiagram)(W);
  }

  /* The eleven-year silence is DRAWN, not captioned. The five era columns come from the
     data; this sixth column is the absence of data, so it is rendered as an annotated void
     rather than added to heritage.json. Without it the chart shows a continuously populated
     century and the second half of its own title ("then goes quiet") survives only in prose. */
  const VOID = { label: '2013\u20132023', l1: 'eleven years,', l2: 'nothing proven' };

  function renderHDiagram(W) {
    const L = { left: 150, right: 18, top: 46, bot: 76, rowH: 34, padY: 14, gap: 62 };
    const nCol = HER.eras.length + 1;                 // five eras plus the void
    const plotW = W - L.left - L.right, eraW = plotW / nCol;
    const xf = (e) => {
      const era = HER.eras[e.era];
      return L.left + e.era * eraW + ((yearFrac(e) - era.from) / (era.to - era.from)) * eraW;
    };
    const rows = HER.collections.map((c) => {
      const evs = HER.events.filter((e) => e.collection === c.key)
        .sort((a, b) => a.date < b.date ? -1 : a.date > b.date ? 1 : 0);
      return { ...c, evs, n: packBy(evs, xf, 38) };
    });
    let y = L.top;
    rows.forEach((r) => { r.y = y; r.h = r.n * L.rowH + L.padY * 2; y += r.h + L.gap; });
    const H = y - L.gap + L.bot;
    const svg = el('svg', { viewBox: `0 0 ${W} ${H}`, role: 'img',
      'aria-label': `Two rows of ${HER.events.length} proven heritage events from ${HER.meta.counts.firstYear} ` +
        `to ${HER.meta.counts.lastYear}, running earlier to later across five era columns that are ` +
        'each the same width however many years the era ran, so distance across is not years: ' +
        HER.eras.map((x) => x.label).join(', ') + ', followed by a sixth column, 2013 to 2023, ' +
        'drawn empty because the register proves nothing in it. Top row: what changed the region’s capacity. ' +
        'Bottom row: what was first understood here. Named labels mark Goodyear 1898, PVC 1926, the first ' +
        'polymer department 1963, the ALCOM center 1991 and the last proven row in 2012. After 2012 the ' +
        'record goes quiet until the 2023 designation. The same rows are in the table below.' });

    /* The axis title, in the gutter beside the era labels. A banded time axis looks linear
       and is not, so it says what horizontal distance means before a reader measures with
       their eye. The arithmetic of the banding stays in the methods. */
    svg.appendChild(el('text', { class: 'era-lab', x: 0, y: L.top - 34 }, 'one column per era'));
    svg.appendChild(el('text', { class: 'era-lab', x: 0, y: L.top - 18 }, 'width is not years'));

    // era columns
    HER.eras.forEach((era, i) => {
      const x0 = L.left + i * eraW;
      svg.appendChild(el('rect', { class: 'era-band' + (i % 2 ? ' alt' : ''),
        x: x0, y: L.top - 8, width: eraW, height: y - L.gap - L.top + 8 }));
      svg.appendChild(el('text', { class: 'era-lab', x: x0 + eraW / 2, y: L.top - 20,
        'text-anchor': 'middle' }, era.label));
      if (i) svg.appendChild(el('line', { class: 'axis-rule', x1: x0, x2: x0, y1: L.top - 8, y2: y - L.gap }));
    });
    // the void column: same width as the eras, and visibly holding nothing
    (function voidCol() {
      const x0 = L.left + HER.eras.length * eraW, yTop = L.top - 8, yBot = y - L.gap;
      svg.appendChild(el('rect', { class: 'era-band void', x: x0, y: yTop, width: eraW,
        height: yBot - yTop }));
      svg.appendChild(el('line', { class: 'void-edge', x1: x0, x2: x0, y1: yTop, y2: yBot }));
      svg.appendChild(el('line', { class: 'void-edge', x1: x0 + eraW, x2: x0 + eraW,
        y1: yTop, y2: yBot }));
      svg.appendChild(el('text', { class: 'era-lab', x: x0 + eraW / 2, y: L.top - 20,
        'text-anchor': 'middle' }, VOID.label));
      const mid = (yTop + yBot) / 2;
      svg.appendChild(el('text', { class: 'void-note', x: x0 + eraW / 2, y: mid - 4,
        'text-anchor': 'middle' }, VOID.l1));
      svg.appendChild(el('text', { class: 'void-note', x: x0 + eraW / 2, y: mid + 14,
        'text-anchor': 'middle' }, VOID.l2));
      svg.appendChild(el('text', { class: 'void-lab', x: x0 + eraW / 2, y: yBot + 18,
        'text-anchor': 'middle' }, 'to the Oct 2023 designation'));
    })();
    // row labels
    rows.forEach((r) => {
      const words = r.name.split(' ');
      const l1 = words.slice(0, 2).join(' '), l2 = words.slice(2).join(' ');
      svg.appendChild(el('text', { class: 'lane-name', x: 0, y: r.y + 24, fill: HCOL[r.key] }, l1));
      if (l2) svg.appendChild(el('text', { class: 'lane-name', x: 0, y: r.y + 44, fill: HCOL[r.key] }, l2));
      svg.appendChild(el('text', { class: 'lane-count', x: 0, y: r.y + (l2 ? 65 : 45) }, `${r.evs.length} events`));
    });
    // marks
    const pos = {};
    rows.forEach((r) => {
      const g = el('g', {});
      r.evs.forEach((e) => {
        const cy = r.y + L.padY + e._row * L.rowH + 10;
        pos[e.id] = { x: e._cx, y: cy, rowBot: r.y + r.h };
        const node = el('g', { class: 'ev hev', 'data-id': e.id, style: `--c:${HCOL[r.key]}`,
          tabindex: '0', role: 'button', 'aria-label': `${hDate(e)}. ${e.title}. ${r.name}.` });
        node.appendChild(el('circle', { class: 'hit', cx: e._cx, cy, r: 14 }));
        node.appendChild(el('circle', { class: 'dot', cx: e._cx, cy, r: 6.5, fill: HCOL[r.key] }));
        g.appendChild(node);
      });
      svg.appendChild(g);
    });
    /* Named labels in the band under each row block, leader up to the dot. The labels are
       de-collided into two tiers: adding the void column narrowed every era column, which
       pushed "1963 · first polymer department" under the plate of "2012 · the last proven
       row" and clipped it mid-word. collide.mjs cannot see this — both are plated on
       purpose — so the spacing is computed here instead. */
    const ann = el('g', {});
    const CW = 6.9;                       // ann-name is 13px bold; ~6.9px a character
    const placed = [];                    // [tier, x0, x1] of labels already laid down
    HANN.map((a) => ({ a, p: pos[a.id] })).filter((r) => r.p)
      .sort((r1, r2) => r1.p.x - r2.p.x)
      .forEach(({ a, p }) => {
        const w = a.text.length * CW + 8;
        const x0 = a.anchor === 'end' ? p.x - w : a.anchor === 'middle' ? p.x - w / 2 : p.x - 4;
        const x1 = x0 + w;
        // per row: two labels in different row blocks sit at different heights and
        // cannot collide, so they must not push each other down a tier
        let tier = 0;
        while (placed.some((q) => q[0] === tier && q[3] === p.rowBot &&
          x0 < q[2] + 6 && x1 > q[1] - 6)) tier++;
        placed.push([tier, x0, x1, p.rowBot]);
        const ly = p.rowBot + 20 + tier * 19;
        ann.appendChild(el('line', { class: 'leader', x1: p.x, x2: p.x,
          y1: p.y + 9, y2: ly - 10 }));
        plated(ann, a.text, p.x, ly, { anchor: a.anchor, class: 'ann-name', cw: CW });
      });
    svg.appendChild(ann);
    /* No bottom caption any more: the void column says it in ink, and the old
       right-anchored sentence was the figure's only floating text edge. */

    proBox.appendChild(svg);
    wireHEvents(svg);
    buildHLegend();
  }

  function buildHLegend() {
    const lg = document.getElementById('pro-legend');
    lg.hidden = false; lg.textContent = '';
    HER.collections.forEach((c, i) => {
      if (i) lg.appendChild(document.createTextNode(' · '));
      lg.appendChild(h('span', { class: 'sw', style: `background:${HCOL[c.key]}` }));
      lg.appendChild(h('b', { text: ' ' + c.name }));
      lg.appendChild(document.createTextNode(': ' + c.gloss));
    });
    lg.appendChild(document.createTextNode('. A dot sits at its first year. Tap any dot for the register’s sentence and source.'));
  }

  /* MOBILE, chart 1. Until 2026-08-28 this was 32 stacked cards, about 8,400px of them,
     under a subtitle that told the reader to look at era columns and two rows. The form is
     kept and transposed instead: the eras become stacked blocks, and inside each block the
     same two collection rows carry the same dots at the same year positions. Nothing is
     dropped or aggregated — all 32 marks are here and still open their source on tap. */
  function renderHCompact(W) {
    const GUT = 14, RIGHT = 8, ROW = 20, LABH = 20, PADB = 14;
    const plotW = W - GUT - RIGHT;
    const cols = HER.eras.concat([{ from: 2012, to: 2023, label: VOID.label, isVoid: true }]);
    const xf = (e) => {
      const era = HER.eras[e.era];
      return GUT + ((yearFrac(e) - era.from) / (era.to - era.from)) * plotW;
    };
    // measure first, draw second: the height has to be known before the viewBox exists
    const blocks = cols.map((era, i) => {
      const bands = era.isVoid ? [] : HER.collections.map((c) => {
        const evs = HER.events.filter((e) => e.era === i && e.collection === c.key)
          .sort((a, b) => a.date < b.date ? -1 : a.date > b.date ? 1 : 0);
        return { key: c.key, evs, n: evs.length ? packBy(evs, xf, 20) : 0 };
      }).filter((b) => b.evs.length);
      return { era, bands };
    });
    let y = 6;
    blocks.forEach((b) => {
      b.y = y; y += LABH;
      b.bands.forEach((bd) => { bd.y = y; y += bd.n * ROW + 4; });
      if (b.era.isVoid) { b.voidY = y; y += 46; }
      y += PADB;
    });
    const H = y;

    const svg = el('svg', { viewBox: `0 0 ${W} ${H}`, role: 'img',
      'aria-label': `${HER.events.length} proven heritage events in six stacked era blocks, ` +
        HER.eras.map((x) => x.label).join(', ') + ' and an empty 2013 to 2023 block. Each block is ' +
        'one era and runs earlier to later across the screen, so distance is not years. Inside each ' +
        'block the top row is what changed the region’s capacity and the bottom row is what was ' +
        'first understood here. The last proven row is 2012 and nothing follows it until the 2023 ' +
        'federal designation. The same rows are in the table below.' });

    blocks.forEach((b) => {
      svg.appendChild(el('text', { class: 'era-lab', x: 0, y: b.y + 11 }, b.era.label));
      const bot = (b.era.isVoid ? b.voidY + 40 : (b.bands.length
        ? b.bands[b.bands.length - 1].y + b.bands[b.bands.length - 1].n * ROW : b.y + LABH));
      if (b.era.isVoid) {
        svg.appendChild(el('rect', { class: 'era-band void', x: 0, y: b.y + LABH - 6,
          width: W, height: 46, rx: 4 }));
        svg.appendChild(el('text', { class: 'void-note', x: GUT, y: b.voidY + 10 }, VOID.l1 + ' ' + VOID.l2));
        svg.appendChild(el('text', { class: 'void-lab', x: GUT, y: b.voidY + 28 },
          'to the Oct 2023 designation'));
        return;
      }
      b.bands.forEach((bd) => {
        svg.appendChild(el('rect', { x: 0, y: bd.y, width: 3, height: bd.n * ROW - 4,
          fill: HCOL[bd.key], rx: 1.5 }));
        const g = el('g', {});
        bd.evs.forEach((e) => {
          const cy = bd.y + 9 + e._row * ROW;
          const node = el('g', { class: 'ev hev', 'data-id': e.id, style: `--c:${HCOL[bd.key]}`,
            tabindex: '0', role: 'button',
            'aria-label': `${hDate(e)}. ${e.title}. ${hKind(e)}.` });
          node.appendChild(el('circle', { class: 'hit', cx: e._cx, cy, r: 13 }));
          node.appendChild(el('circle', { class: 'dot', cx: e._cx, cy, r: 6, fill: HCOL[bd.key] }));
          g.appendChild(node);
        });
        svg.appendChild(g);
      });
      void bot;
    });

    proBox.appendChild(svg);
    wireHEvents(svg);
    buildHLegend();
  }

  function wireHEvents(svg) {
    svg.querySelectorAll('.hev').forEach((n) => {
      const e = HER.events.find((x) => x.id === n.dataset.id);
      n.addEventListener('mouseenter', () => showHTip(n, e));
      n.addEventListener('mouseleave', hideHTip);
      n.addEventListener('focus', () => showHTip(n, e));
      n.addEventListener('blur', hideHTip);
      n.addEventListener('click', () => openHPanel(e));
      n.addEventListener('keydown', (ev) => {
        if (ev.key === 'Enter' || ev.key === ' ') { ev.preventDefault(); openHPanel(e); }
      });
    });
  }
  function showHTip(node, e) {
    hideHTip();
    ptip = h('div', { class: 'tip' }, [
      h('div', { class: 't-d', text: hDate(e) }),
      h('div', { class: 't-t', text: e.title }),
      h('div', { class: 't-o', text: hKind(e) + ' · click for the source' }),
    ]);
    proBox.appendChild(ptip);
    const b = node.getBoundingClientRect(), v = proBox.getBoundingClientRect();
    const left = Math.min(Math.max(8, b.left - v.left - ptip.offsetWidth / 2 + b.width / 2),
      v.width - ptip.offsetWidth - 8);
    ptip.style.left = left + 'px';
    ptip.style.top = Math.max(4, b.top - v.top - ptip.offsetHeight - 12) + 'px';
  }
  const hideHTip = () => { if (ptip) { ptip.remove(); ptip = null; } };

  function openHPanel(e) {
    panel.textContent = '';
    panel.appendChild(h('button', { class: 'p-close', type: 'button', 'aria-label': 'Close',
      onclick: closePanel, text: '×' }));
    panel.appendChild(h('p', { class: 'p-kind', style: `color:${HCOL[e.collection]}`, text: hKind(e) }));
    panel.appendChild(h('h2', { id: 'panel-title', text: e.title }));
    panel.appendChild(h('dl', { class: 'p-meta' }, [
      h('div', {}, [h('dt', { text: 'Date' }), h('dd', { text: hDate(e) })]),
      h('div', {}, [h('dt', { text: 'Register row' }), h('dd', { text: `${e.id} · labeled ${e.label.toLowerCase()}` })]),
    ]));
    panel.appendChild(h('p', { class: 'p-note p-one', text: e.oneLiner }));
    if (e.datePrecision === 'range') panel.appendChild(h('p', { class: 'p-note',
      text: 'Recorded as a span of years; the mark sits at its first year.' }));
    else if (e.datePrecision === 'year') panel.appendChild(h('p', { class: 'p-note',
      text: 'Recorded to the year only; placed mid-year.' }));
    const ul = h('ul', { class: 'p-src' });
    e.sources.forEach((sr) => {
      const li = h('li', {});
      if (sr.url) {
        li.appendChild(h('a', { href: sr.url, text: sr.url.replace(/^https?:\/\/(www\.)?/, '').split(/[/?#]/)[0] }));
        if (sr.note) li.appendChild(document.createTextNode(' · ' + sr.note));
      } else li.appendChild(document.createTextNode(sr.note));
      ul.appendChild(li);
    });
    panel.appendChild(h('h3', { text: e.sources.length === 1 ? 'Source' : 'Sources' }));
    panel.appendChild(ul);
    panel.hidden = false; scrim.hidden = false;
    panel.querySelector('.p-close').focus();
  }

  function buildHTable() {
    const tb = document.querySelector('#htable tbody');
    if (!tb || !HER) return;
    tb.textContent = '';
    HER.events.slice().sort((a, b) => a.date < b.date ? -1 : 1).forEach((e) => {
      const srcs = e.sources.filter((x) => x.url);
      const td = h('td', { class: 't-src' });
      if (srcs.length) {
        td.appendChild(h('a', { href: srcs[0].url, text: 'Source' }));
        if (srcs.length > 1) td.appendChild(document.createTextNode(` +${srcs.length - 1}`));
      }
      tb.appendChild(h('tr', {}, [
        h('td', { class: 't-date', text: hDate(e) }),
        h('td', { text: e.title }),
        h('td', { class: 't-lane', style: `color:${HCOL[e.collection]}`, text: hKind(e) }),
        h('td', { class: 't-one', text: e.oneLiner }),
        td,
      ]));
    });
  }

  /* -------------------------------------------------------- 4 table + csv */
  // Newest first, capped at the 12 most recent delivered events behind a "show all"
  // disclosure — the story owns the scroll, the appendix owns the archive. The status
  // column is gone: every default row is delivered (the caption says so once), and the
  // scheduled rows appear at the end when expanded, each tagged inline.

  function buildTable() {
    const tb = document.querySelector('#dtable tbody');
    tb.textContent = '';
    const del = IN.filter((e) => visible(e) && e.delivered)
      .sort((a, b) => a.date < b.date ? 1 : a.date > b.date ? -1 : 0);
    const sch = IN.filter((e) => visible(e) && !e.delivered)
      .sort((a, b) => a.date < b.date ? -1 : a.date > b.date ? 1 : 0);
    const row = (e) => {
      const tdE = h('td', {}, [document.createTextNode(e.title)]);
      if (!e.delivered) tdE.appendChild(h('span', { class: 'badge', text: 'Scheduled' }));
      return h('tr', {}, [
        h('td', { class: 't-date', text: showDate(e) }),
        tdE,
        h('td', { class: 't-lane', style: `color:${LANE_COLOR[e.laneKey]}`, text: e.lane }),
        h('td', { class: 't-org', text: e.org }),
      ]);
    };
    const yrHead = (label) => h('tr', { class: 'yrhead' },
      [h('th', { colspan: '4', scope: 'colgroup', text: label })]);
    const cap = tableExpanded ? del.length : Math.min(12, del.length);
    let curYr = null;
    del.slice(0, cap).forEach((e) => {
      const yr = e.date.slice(0, 4);
      if (yr !== curYr) { tb.appendChild(yrHead(yr)); curYr = yr; }
      tb.appendChild(row(e));
    });
    if (tableExpanded && sch.length) {
      tb.appendChild(yrHead(`Scheduled ahead · ${sch.length} dates`));
      sch.forEach((e) => tb.appendChild(row(e)));
    }
    const btn = document.getElementById('showall');
    if (btn) {
      btn.hidden = del.length + sch.length <= cap;
      btn.textContent = tableExpanded
        ? 'Show the 12 most recent only'
        : `Show all ${del.length} delivered and ${sch.length} scheduled events`;
    }
  }
  document.getElementById('showall').addEventListener('click', () => {
    tableExpanded = !tableExpanded; buildTable();
  });

  document.getElementById('csv').addEventListener('click', () => {
    const q = (s) => `"${String(s == null ? '' : s).replace(/"/g, '""')}"`;
    const rows = [['Date', 'Date precision', 'Event', 'Workstream', 'Organization', 'Status']
      .map(q).join(',')];
    IN.filter(visible).forEach((e) => rows.push([e.dateDisplay, e.datePrecision, e.title, e.lane,
      e.org, e.delivered ? 'Delivered' : 'Scheduled'].map(q).join(',')));
    const blob = new Blob([rows.join('\n')], { type: 'text/csv;charset=utf-8' });
    const a = h('a', { href: URL.createObjectURL(blob), download: 'pic-timeline.csv' });
    document.body.appendChild(a); a.click(); a.remove();
  });

  /* ------------------------------------------------------ 5 interaction */

  function wireEvents(svg) {
    svg.querySelectorAll('.ev').forEach((n) => {
      const e = IN.find((x) => x.id === n.dataset.id);
      n.addEventListener('mouseenter', () => showTip(n, e));
      n.addEventListener('mouseleave', hideTip);
      n.addEventListener('focus', () => showTip(n, e));
      n.addEventListener('blur', hideTip);
      n.addEventListener('click', () => openPanel(e));
      n.addEventListener('keydown', (ev) => {
        if (ev.key === 'Enter' || ev.key === ' ') { ev.preventDefault(); openPanel(e); }
      });
    });
  }

  function showTip(node, e) {
    hideTip();
    tip = h('div', { class: 'tip' }, [
      h('div', { class: 't-d', text: showDate(e) + (e.delivered ? '' : ' · scheduled') }),
      h('div', { class: 't-t', text: e.title }),
      h('div', { class: 't-o', text: `${e.lane} · ${e.org}` }),
    ]);
    viz.appendChild(tip);
    const b = node.getBoundingClientRect(), v = viz.getBoundingClientRect();
    const left = Math.min(Math.max(8, b.left - v.left - tip.offsetWidth / 2 + b.width / 2),
      v.width - tip.offsetWidth - 8);
    tip.style.left = left + 'px';
    tip.style.top = Math.max(4, b.top - v.top - tip.offsetHeight - 12) + 'px';
  }
  const hideTip = () => { if (tip) { tip.remove(); tip = null; } };

  function openPanel(e) {
    panel.textContent = '';
    panel.appendChild(h('button', { class: 'p-close', type: 'button', 'aria-label': 'Close',
      onclick: closePanel, text: '×' }));
    panel.appendChild(h('p', { class: 'p-kind', style: `color:${LANE_COLOR[e.laneKey]}`, text: e.lane }));
    panel.appendChild(h('h2', { id: 'panel-title', text: e.title }));
    const meta = h('dl', { class: 'p-meta' }, [
      h('div', {}, [h('dt', { text: 'Date' }), h('dd', { text: showDate(e) })]),
      h('div', {}, [h('dt', { text: 'Organization' }), h('dd', { text: e.org })]),
      h('div', {}, [h('dt', { text: 'Status' }),
        h('dd', { text: e.delivered ? 'Delivered' : 'Scheduled, not delivered' })]),
    ]);
    if (e.horizon) meta.appendChild(h('div', {}, [h('dt', { text: 'Time to a result' }),
      h('dd', { text: HZ[e.horizon].label })]));
    panel.appendChild(meta);
    const pn = precNote(e);
    if (pn) panel.appendChild(h('p', { class: 'p-note', text: pn }));
    if (!e.delivered) panel.appendChild(h('p', { class: 'p-note',
      text: 'This is a scheduled date drawn from the award or project record. It is not work already done.' }));
    panel.hidden = false; scrim.hidden = false;
    panel.querySelector('.p-close').focus();
  }
  function closePanel() { panel.hidden = true; scrim.hidden = true; }
  scrim.addEventListener('click', closePanel);
  document.addEventListener('keydown', (e) => { if (e.key === 'Escape') { closePanel(); hideTip(); hideHTip(); } });

  /* --------------------------------------------------------- filters */

  function buildFilters() {
    const lf = document.getElementById('lane-filters');
    DATA.lanes.forEach((ln) => {
      const b = h('button', { class: 'chip', type: 'button', 'aria-pressed': 'true',
        style: `color:${LANE_COLOR[ln.key]}`,
        onclick: () => { offLane.has(ln.key) ? offLane.delete(ln.key) : offLane.add(ln.key);
          b.setAttribute('aria-pressed', String(!offLane.has(ln.key))); refresh(); } }, [
        h('span', { class: 'sw', style: `background:${LANE_COLOR[ln.key]}` }),
        h('span', { text: ln.name }),
      ]);
      lf.appendChild(b);
    });
    const hf = document.getElementById('hz-filters');
    HZ_ORDER.forEach((k) => {
      const b = h('button', { class: 'chip', type: 'button', 'aria-pressed': 'true',
        onclick: () => { offHz.has(k) ? offHz.delete(k) : offHz.add(k);
          b.setAttribute('aria-pressed', String(!offHz.has(k))); refresh(); } },
        [h('span', { text: HZ[k].label })]);
      hf.appendChild(b);
    });
    const reset = document.getElementById('reset');
    reset.addEventListener('click', () => {
      offLane.clear(); offHz.clear();
      document.querySelectorAll('.chip').forEach((c) => c.setAttribute('aria-pressed', 'true'));
      refresh();
    });
  }

  function buildLegend() {
    const lg = document.getElementById('legend');
    lg.textContent = '';
    const grp = (title, items) => h('div', { class: 'grp' },
      [h('span', { class: 'lg-h', text: title }), ...items]);
    const svgDot = (fill, hollow) => {
      const s = document.createElementNS(NS, 'svg');
      s.setAttribute('width', '20'); s.setAttribute('height', '20');
      s.appendChild(el('circle', { cx: 10, cy: 10, r: 7, fill: hollow ? '#fff' : fill,
        stroke: hollow ? fill : '#fff', 'stroke-width': hollow ? 3 : 1.5 }));
      if (hollow) s.appendChild(el('circle', { cx: 10, cy: 10, r: 1.6, fill }));
      return s;
    };
    lg.appendChild(grp('Status', [
      h('span', { class: 'item' }, [svgDot('#06414B', false), h('span', { text: 'Delivered' })]),
      h('span', { class: 'item' }, [svgDot('#06414B', true), h('span', { text: 'Scheduled, not delivered' })]),
    ]));
    lg.appendChild(grp('Size', [
      h('span', { class: 'item' }, [h('span', { text: 'Every dot is the same size; the chips above filter by how long that kind of work takes to show a result.' })]),
    ]));
    lg.hidden = false;
  }

  function refresh() {
    document.getElementById('reset').hidden = !(offLane.size || offHz.size);
    mode = null; render(); buildTable();
  }

  /* ------------------------------------------------------------- boot */

  Promise.all([loadData('timeline.json'), loadData('heritage.json')]).then(([d, hd]) => {
    DATA = d; HER = hd;
    const from = WIN_FROM.getTime();
    d.events.forEach((e) => { (new Date(e.date).getTime() >= from ? IN : PRE).push(e); });
    IN = IN.filter((e) => e.show || !e.delivered);

    // The lede's numbers come from the data, never from the HTML — the static text is
    // only what a reader sees before the JSON arrives (and it is what claims.json guards).
    const hc = HER.meta.counts;
    const put = (id, v) => { const n = document.getElementById(id); if (n) n.textContent = String(v); };
    put('h-shown', hc.shown); put('h-first', hc.firstYear); put('h-last', hc.lastYear);
    put('h-her', hc.heritage); put('h-dis', hc.discoveries);
    const { before, since } = cadenceData();
    put('cad-before', before); put('cad-since', since);
    put('n-fwd', IN.filter((e) => !e.delivered).length);

    /* The hero stat row, through the shared ceremony helper rather than a page-local
       list: four cards, 2x2 on the measure rail, and exactly one carries the accent
       because exactly one of them is the page's finding. Four, not five — the fifth
       wrapped to its own row at 1280 and the workstream count already leads the
       calendar H2. */
    PV.figures([
      ['', hc.shown, 'Proven heritage events', `${hc.firstYear} to ${hc.lastYear}`],
      ['', before, 'Events, 34 months before', 'Up to the October 2023 designation'],
      ['key', since, 'Delivered, 34 months since', 'The same span, to within a day'],
      ['', IN.filter((e) => !e.delivered).length, 'Scheduled ahead',
       'Dates on the record, not yet delivered'],
    ]);

    // The next three scheduled dates, straight from the record.
    const watch = document.getElementById('watch');
    if (watch) {
      IN.filter((e) => !e.delivered && e.date > NOW_ISO)
        .sort((a, b) => a.date < b.date ? -1 : 1).slice(0, 3)
        .forEach((e) => watch.appendChild(h('li', {}, [
          h('b', { text: showDate(e) }),
          document.createTextNode(` ${e.title} · ${e.org}`),
        ])));
    }

    /* The 104 is reconciled to what a reader can count on the page, in one place and from
       the data: 87 drawn on the calendar, 5 before the window, 12 press-coverage rows that
       are reporting ABOUT the cluster rather than things the cluster did. Typing any of
       these would let the apparatus contradict itself, which is how it read before. */
    const nCal = IN.length, nPre = PRE.length;
    const nMedia = d.events.length - nCal - nPre;
    const dropped = hc.dropped['label:CLAIMED'] || 0;
    /* The methodology box is the shared one, injected between the last band and the
       closer like every other page in the room. It used to be a hand-written section
       with its own heading and its own "Reproduce this" renderer, which is how this page
       ended up with a provenance block nobody else had to maintain. The meta below is an
       inline literal rather than a data file's meta block because two registers feed this
       page, and the reconciliation between them is computed here from both. */
    PV.methodology({page: 'timeline', meta: {
      fetched: '13 August 2026',
      source: d.meta.source +
        ` Of those ${d.events.length}, ${nCal} fall inside the 2023 to 2029 calendar window and are ` +
        `drawn there: ${IN.filter((e) => e.delivered).length} delivered and ` +
        `${IN.filter((e) => !e.delivered).length} scheduled. ${nPre} predate the window and feed the ` +
        `year-by-year chart instead. The remaining ${nMedia} are press coverage of the cluster rather ` +
        `than things the cluster did, and are held out of both charts.`,
      sources:
        `The heritage rows come from PIC’s NEO Polymer Wins register, an internal file, as of ` +
        `14 August 2026. Of its ${hc.shown + dropped} heritage and discovery rows, ${hc.shown} are ` +
        `labeled proven and appear here; ${dropped} labeled claimed are withheld. ` +
        `${hc.sourcesStripped} internal source references were stripped in the build, and every row ` +
        `shown carries at least one public source. Shipped products, licenses and living capital are ` +
        `a different register and are not on this page.`,
      row: `One row is one dated public event: something the cluster did, or had done to it, that ` +
        `entered a public record on a date. The ${hc.shown} heritage rows are a separate register ` +
        `and are not part of that count.`,
      definition: 'Each dot is one dated event, in the workstream that produced it. Every dot is the ' +
        'same size: color is the workstream, and a hollow ring with a center pip is a scheduled date. ' +
        'The chips filter by how long that kind of work takes to show a result.',
      bases: 'Dates are shown at the precision they were recorded. Some events are known only to a ' +
        'month or a year, and are placed mid-period rather than pretending to a day.',
      stages: 'Vertical rules and named labels mark the load-bearing events; every other dot opens ' +
        'its title, date and organization on click.',
      derived_note: 'The year-by-year chart counts delivered public events per year from this same ' +
        'record. The 2026 bar covers 1 January to 13 August 2026 and is drawn lighter than the full ' +
        'years beside it. The two century-scale context rows sit in the heritage strip and are not ' +
        'counted in it.',
      composite_note: 'The heritage strip gives every era the same space however many years it ran, ' +
        'plus an empty sixth block for 2013 to 2023, so distance across it is not years. A dot sits ' +
        'at its first year, and tapping it opens the register’s sentence and source.',
      publicOnly: d.meta.publicOnly +
        ' A quiet period on this timeline means nothing was published, not that nothing happened.',
      uncertain: 'Future milestones are drawn hollow because they are plans, not facts. A hollow ' +
        'marker records an intention on a date and is not evidence the thing occurred.',
      caution: 'Dates are the date of public record, which can trail the decision by weeks. The ' +
        'order of two close events is not reliable.',
      not_the_cluster: 'The heritage rows are why the region has this capacity, not what the cluster ' +
        'did. None of them is a cluster outcome, and a discovery (a paper or a patent) is not a product.',
      /* HER.meta.note says this in the register's own voice, with em-dashes the house
         prose ban does not allow, so the sentence is rewritten here rather than piped
         through. Same rule, same five withheld rows. */
      note: 'Heritage rows appear only when PIC’s register labels them proven. Rows it labels ' +
        'claimed, where a date or a figure is recorded two ways, are withheld rather than shown ' +
        'with a caveat; the wartime synthetic-rubber program, its tonnage recorded four ways, is ' +
        'one of them. The register is internal; only the proven rows and their public sources ' +
        'travel to this page.',
      small_numbers: 'The year-by-year record was compiled after the designation, so its early years ' +
        'are under-counted: four is the fewest the before count can be, and seventeen times the most ' +
        'the jump can be.',
    }});

    buildFilters(); buildTable(); render(); renderCadence();
    buildHTable(); renderPrologue();
  }).catch((err) => {
    viz.textContent = '';
    viz.appendChild(h('p', { class: 'nojs',
      text: 'The timeline data could not be loaded. This page must be served over HTTP, not opened as a file.' }));
    console.error(err);
  });

  let t;
  window.addEventListener('resize', () => { clearTimeout(t); t = setTimeout(() => { render(); renderCadence(); renderPrologue(); }, 130); });
})();
