/* Prefer the JSON the bundler inlined; fall back to fetch when the folder is served
   directly. One call site, both modes — the source tree and the published artifact never
   diverge, and a bundled page needs no network at all. */
function loadData(file) {
  var tag = document.querySelector(
    'script[type="application/json"][data-pv-file="' + file + '"]');
  if (tag) return Promise.resolve(JSON.parse(tag.textContent));
  return fetch('data/' + file, {cache: 'no-cache'}).then(function (r) {
    if (!r.ok) throw new Error(r.status + ' ' + r.statusText);
    return r.json();
  });
}

/* =========================================================================
   PIC portfolio timeline
   Vanilla JS, inline SVG. No dependencies, no build step. Everything on this
   page derives from data/timeline.json, which is generated by
   tools/build-timeline-web.py from the merged event inventory. Do not edit the
   JSON by hand — regenerate it.

   Structure
     1  data + scales
     2  layout        lane bands, collision packing, label placement
     3  render        svg (wide) / cards (narrow)
     4  table + csv
     5  interaction   filters, hover, panel, hash routing
   ========================================================================= */

(() => {
  'use strict';

  // Below this the lanes stop being readable as lanes and a card list is honest.
  const CARD_BREAKPOINT = 900;
  // The window. 99 of 104 public events fall inside it; the five older ones are
  // summarized in a band above rather than compressing the axis to nothing.
  const WIN_FROM = new Date('2023-01-01');
  const WIN_TO = new Date('2030-01-01');
  const NOW = new Date('2026-08-13');

  const LANE_COLOR = {
    desig: '#12798B', rd: '#8E3B62', work: '#9A6A08', startup: '#1A8A9E', infra: '#5E7A10',
  };
  const HZ = {
    quick: { r: 5.5, label: 'Under a year' },
    mid: { r: 7, label: 'One to three years' },
    long: { r: 8.5, label: 'Three years or more' },
  };
  const HZ_ORDER = ['quick', 'mid', 'long'];

  let DATA = null, IN = [], PRE = [];
  let HER = null;                       // heritage.json — the prologue's data
  const HCOL = { heritage: '#585955', discoveries: '#8E3B62' };
  const offLane = new Set(), offHz = new Set();
  let mode = null, lastW = 0, tip = null;

  const viz = document.getElementById('viz');
  const panel = document.getElementById('panel');
  const scrim = document.getElementById('scrim');

  const NS = 'http://www.w3.org/2000/svg';
  const el = (t, a, txt) => {
    const n = document.createElementNS(NS, t);
    for (const k in a) if (a[k] != null) n.setAttribute(k, a[k]);
    if (txt != null) n.textContent = txt;
    return n;
  };
  const h = (t, a, kids) => {
    const n = document.createElement(t);
    for (const k in (a || {})) {
      if (k === 'class') n.className = a[k];
      else if (k === 'text') n.textContent = a[k];
      else if (k.startsWith('on')) n.addEventListener(k.slice(2), a[k]);
      else if (a[k] != null) n.setAttribute(k, a[k]);
    }
    (kids || []).forEach((c) => n.appendChild(c));
    return n;
  };

  /* ------------------------------------------------------------- 1 data */

  // Show the date at the precision it is actually known to. An event recorded
  // only to its year is not a 1 January event, and drawing it as one is a lie
  // the reader cannot see.
  const MON = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  function showDate(e) {
    const d = new Date(e.date);
    if (e.datePrecision === 'day') return `${d.getUTCDate()} ${MON[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
    if (e.datePrecision === 'month') return `${MON[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
    return e.dateDisplay;
  }
  const precNote = (e) => e.datePrecision === 'day' ? null
    : e.datePrecision === 'month' ? 'Recorded to the month; placed mid-month.'
    : 'Recorded to the year only; placed mid-year.';

  const visible = (e) => !offLane.has(e.laneKey) && !(e.horizon && offHz.has(e.horizon));

  /* ----------------------------------------------------------- 2 layout */

  // Pack events into sub-rows inside their lane so dots never sit on top of each
  // other. Greedy first-fit by x — the same approach a Gantt uses for bars.
  function pack(events, x, minGap) {
    const rowsEnd = [];
    events.forEach((e) => {
      const cx = x(new Date(e.date));
      let row = rowsEnd.findIndex((end) => cx - end >= minGap);
      if (row === -1) { row = rowsEnd.length; rowsEnd.push(-1e9); }
      rowsEnd[row] = cx;
      e._row = row; e._cx = cx;
    });
    return Math.max(1, rowsEnd.length);
  }

  /* ----------------------------------------------------------- 3 render */

  function render() {
    const w = viz.clientWidth;
    if (!w) return;
    const want = w < CARD_BREAKPOINT ? 'cards' : 'diagram';
    if (want === mode && Math.abs(w - lastW) < 2) return;
    mode = want; lastW = w;
    viz.textContent = '';
    (want === 'cards' ? renderCards : renderDiagram)(w);
  }

  function renderDiagram(W) {
    const L = { left: 208, right: 26, top: 46, bot: 42, laneGap: 10, rowH: 30, padY: 16 };
    const plotW = W - L.left - L.right;
    const span = WIN_TO - WIN_FROM;
    const x = (d) => L.left + ((Math.min(Math.max(d, WIN_FROM), WIN_TO) - WIN_FROM) / span) * plotW;

    const lanes = DATA.lanes.map((ln) => {
      const evs = IN.filter((e) => e.laneKey === ln.key && visible(e))
        .sort((a, b) => new Date(a.date) - new Date(b.date));
      const nRows = pack(evs, x, 19);
      return { ...ln, evs, nRows, all: IN.filter((e) => e.laneKey === ln.key).length };
    });

    let y = L.top;
    lanes.forEach((ln) => { ln.y = y; ln.h = ln.nRows * L.rowH + L.padY * 2; y += ln.h + L.laneGap; });
    const H = y + L.bot;

    const svg = el('svg', { viewBox: `0 0 ${W} ${H}`, role: 'img',
      'aria-label': ariaSummary() });

    // year gridlines + labels
    for (let yr = 2023; yr <= 2030; yr++) {
      const gx = x(new Date(`${yr}-01-01`));
      svg.appendChild(el('line', { class: 'axis-rule', x1: gx, x2: gx, y1: L.top - 14, y2: y - L.laneGap }));
      if (yr < 2030) svg.appendChild(el('text', { class: 'axis-y', x: gx + 7, y: L.top - 20 }, yr));
    }

    // lane bands + names
    lanes.forEach((ln, i) => {
      svg.appendChild(el('rect', { class: 'lane-band' + (i % 2 ? ' alt' : ''),
        x: 0, y: ln.y, width: W, height: ln.h, rx: 8 }));
      svg.appendChild(el('text', { class: 'lane-name', x: 0, y: ln.y + 24,
        fill: LANE_COLOR[ln.key] }, ln.name));
      const shown = ln.evs.length;
      svg.appendChild(el('text', { class: 'lane-count', x: 0, y: ln.y + 45 },
        shown === ln.all ? `${shown} events` : `${shown} of ${ln.all} events`));
    });

    // the "as of" rule — bars/dots to its right are scheduled, not delivered
    const nx = x(NOW);
    svg.appendChild(el('line', { class: 'now-rule', x1: nx, x2: nx, y1: L.top - 14, y2: y - L.laneGap }));
    svg.appendChild(el('text', { class: 'now-lab', x: nx + 8, y: y - L.laneGap + 20 }, 'Today'));

    // events
    lanes.forEach((ln) => {
      const g = el('g', {});
      ln.evs.forEach((e) => {
        const cy = ln.y + L.padY + e._row * L.rowH + L.rowH / 2;
        const r = (HZ[e.horizon] || HZ.mid).r;
        const node = el('g', { class: 'ev' + (e.delivered ? '' : ' fwd'), 'data-id': e.id,
          style: `--c:${LANE_COLOR[ln.key]}`,
          tabindex: '0', role: 'button',
          'aria-label': `${showDate(e)}. ${e.title}.` + (e.delivered ? '' : ' Scheduled, not delivered.') });
        node.appendChild(el('circle', { class: 'hit', cx: e._cx, cy, r: Math.max(13, r + 7) }));
        node.appendChild(el('circle', { class: 'dot', cx: e._cx, cy, r, fill: LANE_COLOR[ln.key],
          stroke: e.delivered ? '#fff' : LANE_COLOR[ln.key] }));
        // A white ring on a pale lane band still needs an anchor at small radii, or it
        // reads as a hole in the chart rather than a mark on it.
        if (!e.delivered) node.appendChild(el('circle', { class: 'pip', cx: e._cx, cy, r: 1.6,
          fill: LANE_COLOR[ln.key] }));
        g.appendChild(node);
      });
      svg.appendChild(g);
    });

    viz.appendChild(svg);
    wireEvents(svg);
    buildLegend();
  }

  function renderCards(W) {
    const list = h('div', { class: 'cards' });
    IN.filter(visible).slice().reverse().forEach((e) => {
      const c = h('div', { class: 'card', style: `border-left-color:${LANE_COLOR[e.laneKey]}` }, [
        h('div', { class: 'c-d', text: showDate(e) }),
        h('div', { class: 'c-t', text: e.title }),
        h('div', { class: 'c-o', text: `${e.lane} · ${e.org}` }),
      ]);
      if (!e.delivered) c.appendChild(h('span', { class: 'c-f', text: 'Scheduled, not delivered' }));
      list.appendChild(c);
    });
    viz.appendChild(list);
    buildLegend();
  }

  function ariaSummary() {
    const n = IN.filter(visible).length;
    const fwd = IN.filter((e) => visible(e) && !e.delivered).length;
    return `Timeline of ${n} public events from 2023 to 2029, in five workstream lanes: ` +
      DATA.lanes.map((l) => l.name).join(', ') + '. Each dot is one dated event; dot size shows how ' +
      `long that kind of work takes to show a result. ${fwd} events are hollow because they are ` +
      'scheduled, not delivered. A dashed rule marks 13 August 2026. The same record is in the table below.';
  }

  /* ------------------------------------------------ 3b the prologue: why here */
  // The heritage rows sit on an ERA-BANDED axis, not the 2023–2029 linear scale: five
  // era columns of equal width, events placed linearly inside their column. 1898–2012 on
  // the operating record's scale would compress to nothing; a linear 114-year axis would
  // put 11 of 32 marks in one 30-year stretch. Equal era columns are the honest middle —
  // and the columns are labeled with their years so nobody reads the axis as linear.
  const proBox = document.getElementById('pro-viz');
  let proMode = null, proW = 0, ptip = null;

  const yearFrac = (e) => {
    const d = new Date(e.date);
    return e.year + (e.datePrecision === 'day' || e.datePrecision === 'month'
      ? (d.getUTCMonth() + (d.getUTCDate() - 1) / 31) / 12 : 0.5);
  };
  function packBy(events, xf, minGap) {
    const rowsEnd = [];
    events.forEach((e) => {
      const cx = xf(e);
      let row = rowsEnd.findIndex((end) => cx - end >= minGap);
      if (row === -1) { row = rowsEnd.length; rowsEnd.push(-1e9); }
      rowsEnd[row] = cx; e._row = row; e._cx = cx;
    });
    return Math.max(1, rowsEnd.length);
  }
  const hDate = (e) => e.dateDisplay;
  const hKind = (e) => (HER.collections.find((c) => c.key === e.collection) || {}).name || e.collection;

  function renderPrologue() {
    if (!HER || !proBox) return;
    const W = proBox.clientWidth;
    if (!W) return;
    const want = W < CARD_BREAKPOINT ? 'cards' : 'diagram';
    if (want === proMode && Math.abs(W - proW) < 2) return;
    proMode = want; proW = W;
    proBox.textContent = '';
    (want === 'cards' ? renderHCards : renderHDiagram)(W);
  }

  function renderHDiagram(W) {
    const L = { left: 150, right: 18, top: 46, bot: 30, rowH: 34, padY: 14, gap: 12 };
    const plotW = W - L.left - L.right, eraW = plotW / HER.eras.length;
    const xf = (e) => {
      const era = HER.eras[e.era];
      return L.left + e.era * eraW + ((yearFrac(e) - era.from) / (era.to - era.from)) * eraW;
    };
    const rows = HER.collections.map((c) => {
      const evs = HER.events.filter((e) => e.collection === c.key)
        .sort((a, b) => a.date < b.date ? -1 : a.date > b.date ? 1 : 0);
      return { ...c, evs, n: packBy(evs, xf, 38) };
    });
    let y = L.top;
    rows.forEach((r) => { r.y = y; r.h = r.n * L.rowH + L.padY * 2; y += r.h + L.gap; });
    const H = y + L.bot;
    const svg = el('svg', { viewBox: `0 0 ${W} ${H}`, role: 'img',
      'aria-label': `Two rows of ${HER.events.length} proven heritage events from ${HER.meta.counts.firstYear} ` +
        `to ${HER.meta.counts.lastYear}, on five era columns of equal width: ` +
        HER.eras.map((x) => x.label).join(', ') + '. Top row: what changed the region\u2019s capacity. ' +
        'Bottom row: what was first understood here. Each dot is one dated event; the same rows are in the table below.' });

    // era columns
    HER.eras.forEach((era, i) => {
      const x0 = L.left + i * eraW;
      svg.appendChild(el('rect', { class: 'era-band' + (i % 2 ? ' alt' : ''),
        x: x0, y: L.top - 8, width: eraW, height: y - L.gap - L.top + 8 }));
      svg.appendChild(el('text', { class: 'era-lab', x: x0 + eraW / 2, y: L.top - 20,
        'text-anchor': 'middle' }, era.label));
      if (i) svg.appendChild(el('line', { class: 'axis-rule', x1: x0, x2: x0, y1: L.top - 8, y2: y - L.gap }));
    });
    // row labels, and a hairline between the two rows so the tenses read as two rows
    rows.forEach((r, i) => {
      if (i) svg.appendChild(el('line', { class: 'axis-rule', x1: 0, x2: W - L.right, y1: r.y - L.gap / 2, y2: r.y - L.gap / 2 }));
      const words = r.name.split(' ');
      const l1 = words.slice(0, 2).join(' '), l2 = words.slice(2).join(' ');
      svg.appendChild(el('text', { class: 'lane-name', x: 0, y: r.y + 24, fill: HCOL[r.key] }, l1));
      if (l2) svg.appendChild(el('text', { class: 'lane-name', x: 0, y: r.y + 44, fill: HCOL[r.key] }, l2));
      svg.appendChild(el('text', { class: 'lane-count', x: 0, y: r.y + (l2 ? 65 : 45) }, `${r.evs.length} events`));
    });
    // marks
    rows.forEach((r) => {
      const g = el('g', {});
      r.evs.forEach((e) => {
        const cy = r.y + L.padY + e._row * L.rowH + 10;
        const node = el('g', { class: 'ev hev', 'data-id': e.id, style: `--c:${HCOL[r.key]}`,
          tabindex: '0', role: 'button', 'aria-label': `${hDate(e)}. ${e.title}. ${r.name}.` });
        node.appendChild(el('circle', { class: 'hit', cx: e._cx, cy, r: 14 }));
        node.appendChild(el('circle', { class: 'dot', cx: e._cx, cy, r: 6.5, fill: HCOL[r.key] }));
        node.appendChild(el('text', { class: 'yr-lab', x: e._cx, y: cy + 19, 'text-anchor': 'middle' },
          String(e.year)));
        g.appendChild(node);
      });
      svg.appendChild(g);
    });
    proBox.appendChild(svg);
    wireHEvents(svg);
    const lg = document.getElementById('pro-legend');
    lg.hidden = false; lg.textContent = '';
    HER.collections.forEach((c, i) => {
      if (i) lg.appendChild(document.createTextNode(' \u00b7 '));
      lg.appendChild(h('span', { class: 'sw', style: `background:${HCOL[c.key]}` }));
      lg.appendChild(h('b', { text: ' ' + c.name }));
      lg.appendChild(document.createTextNode(' \u2014 ' + c.gloss));
    });
    lg.appendChild(document.createTextNode('. A dot sits at its first year; the columns are equal in width, not in years.'));
  }

  function renderHCards() {
    const list = h('div', { class: 'cards' });
    HER.events.slice().sort((a, b) => a.date < b.date ? -1 : 1).forEach((e) => {
      const src = e.sources.find((x) => x.url);
      const c = h('div', { class: 'card', style: `border-left-color:${HCOL[e.collection]}` }, [
        h('div', { class: 'c-d', text: hDate(e) }),
        h('div', { class: 'c-t', text: e.title }),
        h('div', { class: 'c-o', text: e.oneLiner }),
      ]);
      const foot = h('div', { class: 'c-o' }, [h('span', { class: 'c-k', style: `color:${HCOL[e.collection]}`, text: hKind(e) })]);
      if (src) { foot.appendChild(document.createTextNode(' \u00b7 ')); foot.appendChild(h('a', { href: src.url, text: 'Source' })); }
      c.appendChild(foot);
      list.appendChild(c);
    });
    proBox.appendChild(list);
    document.getElementById('pro-legend').hidden = true;
  }

  function wireHEvents(svg) {
    svg.querySelectorAll('.hev').forEach((n) => {
      const e = HER.events.find((x) => x.id === n.dataset.id);
      n.addEventListener('mouseenter', () => showHTip(n, e));
      n.addEventListener('mouseleave', hideHTip);
      n.addEventListener('focus', () => showHTip(n, e));
      n.addEventListener('blur', hideHTip);
      n.addEventListener('click', () => openHPanel(e));
      n.addEventListener('keydown', (ev) => {
        if (ev.key === 'Enter' || ev.key === ' ') { ev.preventDefault(); openHPanel(e); }
      });
    });
  }
  function showHTip(node, e) {
    hideHTip();
    ptip = h('div', { class: 'tip' }, [
      h('div', { class: 't-d', text: hDate(e) }),
      h('div', { class: 't-t', text: e.title }),
      h('div', { class: 't-o', text: hKind(e) + ' \u00b7 click for the source' }),
    ]);
    proBox.appendChild(ptip);
    const b = node.getBoundingClientRect(), v = proBox.getBoundingClientRect();
    const left = Math.min(Math.max(8, b.left - v.left - ptip.offsetWidth / 2 + b.width / 2),
      v.width - ptip.offsetWidth - 8);
    ptip.style.left = left + 'px';
    ptip.style.top = Math.max(4, b.top - v.top - ptip.offsetHeight - 12) + 'px';
  }
  const hideHTip = () => { if (ptip) { ptip.remove(); ptip = null; } };

  function openHPanel(e) {
    panel.textContent = '';
    panel.appendChild(h('button', { class: 'p-close', type: 'button', 'aria-label': 'Close',
      onclick: closePanel, text: '\u00d7' }));
    panel.appendChild(h('p', { class: 'p-kind', style: `color:${HCOL[e.collection]}`, text: hKind(e) }));
    panel.appendChild(h('h2', { id: 'panel-title', text: e.title }));
    panel.appendChild(h('dl', { class: 'p-meta' }, [
      h('div', {}, [h('dt', { text: 'Date' }), h('dd', { text: hDate(e) })]),
      h('div', {}, [h('dt', { text: 'Register row' }), h('dd', { text: `${e.id} \u00b7 labeled ${e.label.toLowerCase()}` })]),
    ]));
    panel.appendChild(h('p', { class: 'p-note p-one', text: e.oneLiner }));
    if (e.datePrecision === 'range') panel.appendChild(h('p', { class: 'p-note',
      text: 'Recorded as a span of years; the mark sits at its first year.' }));
    else if (e.datePrecision === 'year') panel.appendChild(h('p', { class: 'p-note',
      text: 'Recorded to the year only; placed mid-year.' }));
    const ul = h('ul', { class: 'p-src' });
    e.sources.forEach((sr) => {
      const li = h('li', {});
      if (sr.url) {
        li.appendChild(h('a', { href: sr.url, text: sr.url.replace(/^https?:\/\/(www\.)?/, '').split(/[/?#]/)[0] }));
        if (sr.note) li.appendChild(document.createTextNode(' \u2014 ' + sr.note));
      } else li.appendChild(document.createTextNode(sr.note));
      ul.appendChild(li);
    });
    panel.appendChild(h('h3', { text: e.sources.length === 1 ? 'Source' : 'Sources' }));
    panel.appendChild(ul);
    panel.hidden = false; scrim.hidden = false;
    panel.querySelector('.p-close').focus();
  }

  function buildHTable() {
    const tb = document.querySelector('#htable tbody');
    if (!tb || !HER) return;
    tb.textContent = '';
    HER.events.slice().sort((a, b) => a.date < b.date ? -1 : 1).forEach((e) => {
      const srcs = e.sources.filter((x) => x.url);
      const td = h('td', {});
      if (srcs.length) {
        td.appendChild(h('a', { href: srcs[0].url, text: 'Source' }));
        if (srcs.length > 1) td.appendChild(document.createTextNode(` +${srcs.length - 1}`));
      }
      tb.appendChild(h('tr', {}, [
        h('td', { class: 't-date', text: hDate(e) }),
        h('td', { text: e.title }),
        h('td', { class: 't-lane', style: `color:${HCOL[e.collection]}`, text: hKind(e) }),
        h('td', { class: 't-one', text: e.oneLiner }),
        td,
      ]));
    });
  }

  /* -------------------------------------------------------- 4 table + csv */

  function buildTable() {
    const tb = document.querySelector('#dtable tbody');
    tb.textContent = '';
    IN.filter(visible).forEach((e) => {
      tb.appendChild(h('tr', {}, [
        h('td', { class: 't-date', text: showDate(e) }),
        h('td', { text: e.title }),
        h('td', { class: 't-lane', style: `color:${LANE_COLOR[e.laneKey]}`, text: e.lane }),
        h('td', { text: e.org }),
        h('td', { class: 't-st', text: e.delivered ? 'Delivered' : 'Scheduled' }),
      ]));
    });
  }

  document.getElementById('csv').addEventListener('click', () => {
    const q = (s) => `"${String(s == null ? '' : s).replace(/"/g, '""')}"`;
    const rows = [['Date', 'Date precision', 'Event', 'Workstream', 'Organization', 'Status']
      .map(q).join(',')];
    IN.filter(visible).forEach((e) => rows.push([e.dateDisplay, e.datePrecision, e.title, e.lane,
      e.org, e.delivered ? 'Delivered' : 'Scheduled'].map(q).join(',')));
    const blob = new Blob([rows.join('\n')], { type: 'text/csv;charset=utf-8' });
    const a = h('a', { href: URL.createObjectURL(blob), download: 'pic-timeline.csv' });
    document.body.appendChild(a); a.click(); a.remove();
  });

  /* ------------------------------------------------------ 5 interaction */

  function wireEvents(svg) {
    svg.querySelectorAll('.ev').forEach((n) => {
      const e = IN.find((x) => x.id === n.dataset.id);
      n.addEventListener('mouseenter', () => showTip(n, e));
      n.addEventListener('mouseleave', hideTip);
      n.addEventListener('focus', () => showTip(n, e));
      n.addEventListener('blur', hideTip);
      n.addEventListener('click', () => openPanel(e));
      n.addEventListener('keydown', (ev) => {
        if (ev.key === 'Enter' || ev.key === ' ') { ev.preventDefault(); openPanel(e); }
      });
    });
  }

  function showTip(node, e) {
    hideTip();
    tip = h('div', { class: 'tip' }, [
      h('div', { class: 't-d', text: showDate(e) + (e.delivered ? '' : ' · scheduled') }),
      h('div', { class: 't-t', text: e.title }),
      h('div', { class: 't-o', text: `${e.lane} · ${e.org}` }),
    ]);
    viz.appendChild(tip);
    const b = node.getBoundingClientRect(), v = viz.getBoundingClientRect();
    const left = Math.min(Math.max(8, b.left - v.left - tip.offsetWidth / 2 + b.width / 2),
      v.width - tip.offsetWidth - 8);
    tip.style.left = left + 'px';
    tip.style.top = Math.max(4, b.top - v.top - tip.offsetHeight - 12) + 'px';
  }
  const hideTip = () => { if (tip) { tip.remove(); tip = null; } };

  function openPanel(e) {
    panel.textContent = '';
    panel.appendChild(h('button', { class: 'p-close', type: 'button', 'aria-label': 'Close',
      onclick: closePanel, text: '×' }));
    panel.appendChild(h('p', { class: 'p-kind', style: `color:${LANE_COLOR[e.laneKey]}`, text: e.lane }));
    panel.appendChild(h('h2', { id: 'panel-title', text: e.title }));
    const meta = h('dl', { class: 'p-meta' }, [
      h('div', {}, [h('dt', { text: 'Date' }), h('dd', { text: showDate(e) })]),
      h('div', {}, [h('dt', { text: 'Organization' }), h('dd', { text: e.org })]),
      h('div', {}, [h('dt', { text: 'Status' }),
        h('dd', { text: e.delivered ? 'Delivered' : 'Scheduled, not delivered' })]),
    ]);
    if (e.horizon) meta.appendChild(h('div', {}, [h('dt', { text: 'Time to a result' }),
      h('dd', { text: HZ[e.horizon].label })]));
    panel.appendChild(meta);
    const pn = precNote(e);
    if (pn) panel.appendChild(h('p', { class: 'p-note', text: pn }));
    if (!e.delivered) panel.appendChild(h('p', { class: 'p-note',
      text: 'This is a scheduled date drawn from the award or project record. It is not work already done.' }));
    panel.hidden = false; scrim.hidden = false;
    panel.querySelector('.p-close').focus();
  }
  function closePanel() { panel.hidden = true; scrim.hidden = true; }
  scrim.addEventListener('click', closePanel);
  document.addEventListener('keydown', (e) => { if (e.key === 'Escape') { closePanel(); hideTip(); hideHTip(); } });

  /* --------------------------------------------------------- filters */

  function buildFilters() {
    const lf = document.getElementById('lane-filters');
    DATA.lanes.forEach((ln) => {
      const b = h('button', { class: 'chip', type: 'button', 'aria-pressed': 'true',
        style: `color:${LANE_COLOR[ln.key]}`,
        onclick: () => { offLane.has(ln.key) ? offLane.delete(ln.key) : offLane.add(ln.key);
          b.setAttribute('aria-pressed', String(!offLane.has(ln.key))); refresh(); } }, [
        h('span', { class: 'sw', style: `background:${LANE_COLOR[ln.key]}` }),
        h('span', { text: ln.name }),
      ]);
      lf.appendChild(b);
    });
    const hf = document.getElementById('hz-filters');
    HZ_ORDER.forEach((k) => {
      const b = h('button', { class: 'chip', type: 'button', 'aria-pressed': 'true',
        onclick: () => { offHz.has(k) ? offHz.delete(k) : offHz.add(k);
          b.setAttribute('aria-pressed', String(!offHz.has(k))); refresh(); } },
        [h('span', { text: HZ[k].label })]);
      hf.appendChild(b);
    });
    const reset = document.getElementById('reset');
    reset.addEventListener('click', () => {
      offLane.clear(); offHz.clear();
      document.querySelectorAll('.chip').forEach((c) => c.setAttribute('aria-pressed', 'true'));
      refresh();
    });
  }

  function buildLegend() {
    const lg = document.getElementById('legend');
    lg.textContent = '';
    const grp = (title, items) => h('div', { class: 'grp' },
      [h('span', { class: 'lg-h', text: title }), ...items]);
    const svgDot = (fill, hollow) => {
      const s = document.createElementNS(NS, 'svg');
      s.setAttribute('width', '20'); s.setAttribute('height', '20');
      s.appendChild(el('circle', { cx: 10, cy: 10, r: 7, fill: hollow ? '#fff' : fill,
        stroke: hollow ? fill : '#fff', 'stroke-width': hollow ? 3 : 1.5 }));
      if (hollow) s.appendChild(el('circle', { cx: 10, cy: 10, r: 1.6, fill }));
      return s;
    };
    lg.appendChild(grp('Status', [
      h('span', { class: 'item' }, [svgDot('#12798B', false), h('span', { text: 'Delivered' })]),
      h('span', { class: 'item' }, [svgDot('#12798B', true), h('span', { text: 'Scheduled, not delivered' })]),
    ]));
    lg.appendChild(grp('Dot size — time to a visible result', HZ_ORDER.map((k) => {
      const s = document.createElementNS(NS, 'svg');
      s.setAttribute('width', '22'); s.setAttribute('height', '22');
      s.appendChild(el('circle', { cx: 11, cy: 11, r: HZ[k].r, fill: '#585955', stroke: '#fff' }));
      return h('span', { class: 'item' }, [s, h('span', { text: HZ[k].label })]);
    })));
    lg.hidden = false;
  }

  function refresh() {
    document.getElementById('reset').hidden = !(offLane.size || offHz.size);
    mode = null; render(); buildTable();
  }

  /* ------------------------------------------------------------- boot */

  Promise.all([loadData('timeline.json'), loadData('heritage.json')]).then(([d, hd]) => {
    DATA = d; HER = hd;
    const from = WIN_FROM.getTime();
    d.events.forEach((e) => { (new Date(e.date).getTime() >= from ? IN : PRE).push(e); });
    IN = IN.filter((e) => e.show || !e.delivered);

    // The lede's numbers come from the data, never from the HTML — the static text is
    // only what a reader sees before the JSON arrives (and it is what claims.json guards).
    const hc = HER.meta.counts;
    const put = (id, v) => { const n = document.getElementById(id); if (n) n.textContent = String(v); };
    put('h-shown', hc.shown); put('h-first', hc.firstYear); put('h-last', hc.lastYear);
    put('h-her', hc.heritage); put('h-dis', hc.discoveries);
    put('pro-range', `${hc.firstYear} to ${hc.lastYear}`);

    document.getElementById('topline').innerHTML = '';
    [[hc.shown, `proven heritage events, ${hc.firstYear}\u2013${hc.lastYear}`],
     [IN.length, 'public events shown'],
     [IN.filter((e) => e.delivered).length, 'delivered since 2023'],
     [IN.filter((e) => !e.delivered).length, 'scheduled ahead'],
     [d.lanes.length, 'workstreams, in parallel']].forEach(([n, l]) => {
      document.getElementById('topline').appendChild(h('li', {}, [
        h('b', { text: String(n) }), h('span', { text: l })]));
    });

    // Context-tier rows (the old "Rubber Capital, 1900" one-liners) are superseded by the
    // sourced heritage prologue above; only PIC-era pre-2023 events are listed here.
    const preShown = PRE.filter((e) => e.tier !== 'CTX');
    const pw = document.getElementById('pre-window');
    if (preShown.length) {
      pw.appendChild(h('p', {}, [
        h('b', { text: 'Before this window. ' }),
        document.createTextNode(preShown.map((e) => `${e.dateDisplay} ${e.title}`).join(' \u00b7 ') +
          '. The timeline opens at the 2023 federal designation \u2014 the first event with money behind it. ' +
          'Everything earlier is the heritage record above.'),
      ]));
    }

    document.getElementById('m-source').textContent = d.meta.source;
    document.getElementById('m-public').textContent = d.meta.publicOnly;
    const dropped = hc.dropped['label:CLAIMED'] || 0;
    document.getElementById('m-heritage').textContent =
      `The heritage rows come from PIC\u2019s NEO Polymer Wins register, an internal file. Of its ` +
      `${hc.shown + dropped} heritage and discovery rows, ${hc.shown} are labeled proven and appear here; ` +
      `${dropped} labeled claimed are withheld. ${hc.sourcesStripped} internal source references were ` +
      `stripped in the build, and every row shown carries at least one public source. Shipped products, ` +
      `licenses and living capital are a different register and are not on this page.`;
    const notes = document.getElementById('m-notes');
    [['Each dot is one dated event, in the workstream that produced it.',],
     ['Dot size is how long that kind of work takes to show a result — not how important it is.'],
     ['Hollow dots to the right of the dashed rule are scheduled dates from the award record, not work already done.'],
     ['Dates are shown at the precision they were recorded. Some events are known only to a month or a year, and are placed mid-period rather than pretending to a day.'],
     ['The heritage chart above the record uses five era columns of equal width, so its axis is not linear; a dot sits at its first year, and clicking it opens the register’s sentence and source.'],
    ].forEach(([t]) => notes.appendChild(h('li', { text: t })));

    buildFilters(); buildTable(); render();
    buildHTable(); renderPrologue();
  }).catch((err) => {
    viz.textContent = '';
    viz.appendChild(h('p', { class: 'nojs',
      text: 'The timeline data could not be loaded. This page must be served over HTTP, not opened as a file.' }));
    console.error(err);
  });

  let t;
  window.addEventListener('resize', () => { clearTimeout(t); t = setTimeout(() => { render(); renderPrologue(); }, 130); });
})();
