/* The gallery. Cards are grouped by what each piece is FOR, not by data source — a reader
   arrives with a question, not with a preference for QCEW. Claim counts come from
   counts.json, not from this file, and the index-counts claim checks them against the
   harness — so this page cannot drift away from it without the harness saying so. */
(async () => {
"use strict";
/* Counts come from _data/build/derive_index.py, which reads every claims.json. They
   were hand-typed once and immediately drifted — the page said 61 claims and "sixteen
   pieces" while the harness said 62 and 17. */
const C = await PV.data("counts.json");
const cnt = s => C.pages[s] || {claims: 0, manual: 0};
const ALL = [
 {s:"peers", g:"position", t:"First In The Nation", q:"Where does the region actually rank?",
  f:"Ohio is first in the US in plastics and rubber jobs — NAICS 326, private, 2024, all 51 states disclosed. Akron is 6th among the 155 metros that disclose; 227 withhold and are simply unknown.",
  foot:"PIC-12", claims:6, lead:true},
 {s:"location-quotient", g:"position", t:"A Number We Own", q:"How concentrated is the cluster, really?",
  f:"Eleven years of concentration computed from free BLS components, reproduced to within 0.005 of the figure BLS publishes itself. Each NAICS labeled by measurement register.",
  foot:"PIC-12", claims:6, lead:true},
 {s:"laborshed", g:"workforce", t:"No County Is A Labor Market", q:"Is a single county a meaningful unit for workforce policy?",
  f:"Not one of the twelve counties has 69% of its jobs held by its own residents. Summit, the cluster's center, is at 48.4% — most people working there live somewhere else.",
  foot:"PIC-12", claims:5, manual:1, lead:true},
 {s:"churn", g:"workforce", t:"The Churn Engine", q:"Is the workforce stable, or just flat?",
  f:"111,529 hire events and 111,361 separations for 168 net jobs across fourteen years — a flow more than a thousand times larger than the number anyone is scored on.",
  foot:"PIC-12", claims:4},
 {s:"wages", g:"workforce", t:"Does The Cluster Pay Better?", q:"Are these actually good jobs?",
  f:"In 40 of 51 disclosed cells the mean polymer wage beats the county all-industry mean — a real result against a deliberately low bar.",
  foot:"PIC-12", claims:2},
 {s:"occupations", g:"workforce", t:"The Occupations Inside Polymer Manufacturing", q:"Which jobs is the industry made of, and what do they pay here?",
  f:"One in nine is a molding-machine setter. Four Northeast Ohio metros pay the floor jobs near the national rate and the degree jobs under it — nominal, all-industry, before any cost-of-living adjustment.",
  foot:"metro, not PIC-12", claims:12},
 {s:"realwage", g:"conditions", t:"What The Paycheck Buys", q:"Are the wages good after cost of living?",
  f:"Akron ranks 33rd of 56 polymer metros in dollars and 19th in what those dollars buy. But 110 metros are cheaper — the advantage is against this industry's geography, not the country.",
  foot:"metros", claims:4},
 {s:"cost-scissors", g:"conditions", t:"Nothing Came Back Down", q:"Where in the chain did the price spike stick?",
  f:"Gas gave back 104% of its spike, crude 54%, resin 33%, finished product nothing at all. Retracement falls monotonically with distance from the wellhead.",
  foot:"national", claims:5, manual:1},
 {s:"federal-money", g:"money", t:"The Other Federal Money", q:"What federal money reaches polymer manufacturers?",
  f:"$280M in 2025 dollars over eight years. The largest recipient is not tire manufacturing but a residual category — and university awards are invisible to this view by construction.",
  foot:"PIC-12", claims:3},
 {s:"revisions", g:"method", t:"Every Number Moves", q:"How much do these figures change after publication?",
  f:"Almost every month of three producer-price series moved after publication, by a median of 0.15%. Small — and that being small is the finding.",
  foot:"national", claims:2},
 {s:"funding-map", g:"money", t:"PIC Funding Map", q:"Where did the public money go?",
  f:"Three awards, seven programs, every named recipient, with the disclosures attached. Predates the shared house style.",
  foot:"awards", legacy:true},
 {s:"timeline", g:"method", t:"Why Here, Then The Record", q:"Why is the cluster here — and what has it done?",
  f:"32 proven heritage events from 1898 on an era-banded axis, then 87 dated public events since 2023 in lanes, future milestones hollow so a plan never reads as a fact. Predates the shared house style; carries a claims file.",
  foot:"public record + wins register", legacy:true},

 /* 10 further pieces exist and are not published — see the README.
    Their entries are removed here rather than filtered at render time, so the
    text is absent from what is served, not merely unrendered. */
];
/* THE HUB LINKS WHAT EXISTS, NOTHING ELSE. counts.json is generated by derive_index.py
   from the artifact folders actually present in the tree it runs in, so this one filter
   does two jobs: internally every card shows, and in the public tree — where only the
   pages John marked `publish` in _data/ARTIFACT-REVIEW.md were ever copied — the held
   pages disappear on their own. A second hand-maintained publish list would be a second
   thing to forget, and forgetting THIS one publishes a dead link straight to a page that
   was withheld on purpose. */
const A = ALL.filter(x => C.pages[x.s]);
const GRP = {position:"National position", workforce:"Workforce", programs:"PIC programs",
  capability:"Regional capability", money:"Money", conditions:"Operating conditions",
  method:"Method & governance"};
const totalClaims = C.total_claims;
const totalManual = C.total_manual;

PV.figures([
  ["key", C.n_pieces, "interactive pieces", "each self-contained, each reproducible"],
  ["", totalClaims, "checked claims", totalManual + " of them need a human"],
  /* Named in plain terms, not as eight initialisms. A hero stat tile is not caught by
     the body-copy audit, but a reader meets it before anything else on the site —
     the precise program names live in each page's source line, which is their contract. */
  ["", "8", "public data sources", "all federal, all free; each one named on the page that uses it"],
  ["", "0", "private dependencies", "nothing reads or writes production"]
]);

const card = x => `<a class="card" href="../${x.s}/">
  <div class="grp">${GRP[x.g]}</div>
  <h3>${x.t}</h3>
  <p class="q">${x.q}</p>
  <p class="f">${x.f}</p>
  <div class="meta">
    <span class="pill${x.foot === "NEO-14" ? " n14" : ""}">${x.foot}</span>
    ${cnt(x.s).claims ? `<span class="pill">${cnt(x.s).claims} claims</span>` : ""}
    ${cnt(x.s).manual ? `<span class="pill man">${cnt(x.s).manual} manual</span>` : ""}
    ${x.legacy ? `<span class="pill">legacy</span>` : ""}
  </div></a>`;
document.getElementById("lead").innerHTML = A.filter(x => x.lead).map(card).join("");
const order = ["position", "workforce", "capability", "programs", "money", "conditions",
  "method"];
document.getElementById("all").innerHTML =
  order.flatMap(g => A.filter(x => x.g === g && !x.lead)).map(card).join("");
PV.padGrid(".cards", "card");

document.getElementById("footnote").innerHTML =
  `<b>${totalManual} of the ${totalClaims} claims cannot be machine-checked.</b> They are
   quoted from project narratives, press releases and internal registers rather than from
   datasets — the 6PPD page and the commercialization ledger are almost entirely of this
   kind. They carry a source and a falsification condition but no runnable assertion, so
   they are where a wrong reading is most likely to survive. Attack them first.`;

/* Standard methodology + AI disclosure. Generated, not written — see picviz.js. */
await PV.methodology({
  /* Points at _data/SOURCES.json, not at _data/PIPELINES.md. PIPELINES.md is an internal
     working document and is not published, so naming it here sent every public reader to a
     path that does not exist — on the one page that exists to tell them where to look. */
  meta: {source: "Every dataset behind these pages is registered in _data/SOURCES.json " +
                 "with its endpoint, its exact filter values, and the script that fetched " +
                 "it. The methods and the known limits are in _data/METHODS-SOP.md."},
  sourcesNote: "Named on each page this one links to; the register is _data/SOURCES.json.",
  definitions: `<b>PIC-12</b> is the federal-data footprint and matches the cluster-health
    dashboard. <b>NEO-14</b> is how company records are tagged in the vault. They share ten
    counties and are never combined. PIC's measurement register is 3252 + 3255 + 326.`,
  noClaimsNote: `This page makes no numeric claim of its own. The counts above are
    generated from every artifact's claims file by <span class="mono">derive_index.py</span>,
    so they cannot drift from the harness — they were hand-typed once and were wrong within
    a day.`});
})();
